### ISSUE TITLE
予定に重みをつける機能

### ISSUE THREAD

**Issue by satsuki2200** [jphacks/os_2408#2]
ユーザーが優先度を高中低で選べる
プルダウンで実装

**Comment by satsuki2200** [comment]
すでにmainブランチで実装されてるので、お手すきの際に動作確認、issue閉じをしていただけますでしょうか:man_bowing:
(とりあえずバックの方々メンションした)

@gohan5858 @yuto-trd @Inlet-back

**Comment by marutyan** [comment]
フロント担当として重みつきは実装しております。
@gohan5858 も了承済みです
