### ISSUE TITLE
ファイルの分離

### ISSUE THREAD

**Issue by satsuki2200** [jphacks/os_2408#47]
`task_yell/src/app/enhanced-calendar-todo-app/page.tsx`にさまざまな関数をベタ書きしてるので、これらのうち分離やコンポーネント化できるものは分ける。

**Comment by satsuki2200** [comment]
人力マージがある程度終わってから取り組んでいただけるとありがたいです:man_bowing:

**Comment by gohan5858** [comment]
Finish
