### ISSUE TITLE
アプリ名考える

### ISSUE THREAD

**Issue by satsuki2200** [jphacks/os_2408#48]
アプリ名考えてください
いい案があれば書いてください

アプリ名決まったら、カレンダーの上部にアプリ名書いた方がいいかもです

**Comment by satsuki2200** [comment]
@kdix-23-071
なんかコメント書いてください
そしたらたぶん追加できるようになると思います
追加できないのはおそらくコントリビューターに入ってないからかと。

**Comment by satsuki2200** [comment]
これさ、よう考えたらtask_yellって名前あったやんって寝ながら思ったので書いとく
名前がこれでいいなら（逆にこれ以外の選択肢たぶんないだろうけど）、アプリ名を上部に持ってくるかどうかを決めましょう

**Comment by gohan5858** [comment]
Task_yellで決まり！
