### ISSUE TITLE
アプリの設定画面

### ISSUE THREAD

**Issue by yuto-trd** [jphacks/os_2408#66]
バックエンドの都合上以下は必須です
- 通知の有効化ボタン
- 通知に使用する電話番号

**Comment by kdix-23-071** [comment]
設定画面で入力させる形でいけそう？

**Comment by yuto-trd** [comment]
うん

**Comment by yuto-trd** [comment]
あと、Googleカレンダーからのインポートボタンも設定に表示させる？

**Comment by kdix-23-071** [comment]
それが良さげだね
またmoc追加しときます

**Comment by kdix-23-071** [comment]
今んとこの設定項目
- 通知
- 友達
- インポート
- ログアウト

なんだけど、他にいる機能ある？
個人的には言語選択はいらんし、招待拒否は友達の中で終わらせればいいかなと

**Comment by satsuki2200** [comment]
@kdix-23-071 が実装してGitHubにコードあげてくれたので人力マージします

**Comment by satsuki2200** [comment]
@kdix-23-071 
ハンバーガーメニュー実装した時のスクショほしいです

**Comment by kdix-23-071** [comment]
<img width="582" alt="スクリーンショット 2024-10-27 10 32 38" src="https://github.com/user-attachments/assets/b0b3d05f-5159-44c2-baf6-9b5386161b1a">

**Comment by kdix-23-071** [comment]
<img width="424" alt="スクリーンショット 2024-10-27 10 36 28" src="https://github.com/user-attachments/assets/2591f4ce-adfd-4771-8bfa-aab39765fdbd">

**Comment by satsuki2200** [comment]
こんな感じでどうでしょうか
<img width="1469" alt="スクリーンショット 2024-10-27 10 38 42" src="https://github.com/user-attachments/assets/5296468d-4593-4659-acdf-abed2ce3be91">

**Comment by satsuki2200** [comment]
ダークモードの時
<img width="1469" alt="スクリーンショット 2024-10-27 10 39 14" src="https://github.com/user-attachments/assets/0774b3d1-42c9-4d59-860a-12e4eb7f2249">

**Comment by satsuki2200** [comment]
よければプルリクします

**Comment by satsuki2200** [comment]
通知開いた時こんな感じ。
バックと繋ぎこみしてないので、友達やインポートの部分はクリックしても何も表示されないようになっています。
<img width="1469" alt="スクリーンショット 2024-10-27 10 40 06" src="https://github.com/user-attachments/assets/d1a8cf9b-c309-40a4-ae94-507582a6482f">

**Comment by kdix-23-071** [comment]
良いと思います！
